# Generated by Django 4.2.6 on 2023-10-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='count_comment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='count_sukien',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='count_view',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_register',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_register',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_avatar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.TextField(null=True),
        ),
    ]
